### ISSUE TITLE
Название сущности

### ISSUE THREAD

**Issue by bublikOff** [airens/tion_home_assistant#1]
На текущий моменту меня установлен один тион, но квартира будет дооборудована вторым тионом и маджиком. Собственно все куплено. Осталось ремонт во второй комнате закончить. Подключил сейчас ваш плагин к HA и возник вопрос а каким будет идентификатор сущности? Те индикаторы которые повсплывали не имеет условной нумерации либо названия комнаты. Было бы не плохо если плагин смог отработать данную ситуацию

**Comment by airens** [comment]
> На текущий моменту меня установлен один тион, но квартира будет дооборудована вторым тионом и маджиком. Собственно все куплено. Осталось ремонт во второй комнате закончить. Подключил сейчас ваш плагин к HA и возник вопрос а каким будет идентификатор сущности? Те индикаторы которые повсплывали не имеет условной нумерации либо названия комнаты. Было бы не плохо если плагин смог отработать данную ситуацию

Идентификатор будет таким, каким его выдает Magic Air в поле "name". У меня это "Tion Breezer 3S" и "Tion Breezer 3S_2". Добавлять комнату в entity_id неправильно, т.к. зачастую она на русском. Если вам не нравятся имена, которые выдает плагин, то Home Assistant даёт возможность переименовывать девайсы, поэтому вы всегда можете это сделать там.
