### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by mapkepp** [airens/tion_home_assistant#10]
Здравствуйте пол ночи пытаюсь запустить в home assist Tion, как только не пробовал, все равно ошибку выдает:
Invalid config
The following integrations and platforms could not be set up:

tion
Please check your config.

и нигде не появляется
помогите пожалуйста, очень хочится на основании показаний датчиков magik Air, настраивать работу увлажнителя xiaomi, долго гуглил увидель что это возможно только через хоум асистент, а почему то не получается

**Comment by airens** [comment]
Это не имеет отношения к интеграции, смотрите логи HA и внимательно перепроверьте то, что вы написали в конфиге.
