### ISSUE TITLE
NaN - срабатывает триггер

### ISSUE THREAD

**Issue by allmoney** [airens/tion_home_assistant#12]
Добрый день!

Столкнулся с такой проблемой.
Когда с датчика CO2 не получаются данные из-за плохого сигнала - в HA я вижу значение NaN, что расценивается как true для триггера в автоматизации:
```
  - above: 26
    entity_id: sensor.modul_co2_2_temperature
    platform: numeric_state
    for: '00:05:00'
```

Как этого избежать?

**Comment by Paradoxx82** [comment]
Привет! Я избежал этого путем Condition NOT и state: "NaN"

**Comment by airens** [comment]
Да, я не считаю это проблемой компонента, т.к. просто транслирую в HA то, что выдает сервер. Что вы дальше делаете с этим значением - исключительно ваше дело
