### ISSUE TITLE
Режим забора воздуха

### ISSUE THREAD

**Issue by Daemon256** [airens/tion_home_assistant#14]
Приветствую.
Могли бы вы добавить возможность управлять режимом забора воздуха: улица, комната, смешанный?

gate: inside

**Comment by artkos2** [comment]
Присоединяюсь!

**Comment by airens** [comment]
@Daemon256 @artkos2 Объясните мне, глупому, зачем покупать проветриватель, а потом на нем включать забор из комнаты? Купите себе очиститель воздуха, толку будет столько же, а цена - дешевле

**Comment by Daemon256** [comment]
> @Daemon256 @artkos2 Объясните мне, глупому, зачем покупать проветриватель, а потом на нем включать забор из комнаты? Купите себе очиститель воздуха, толку будет столько же, а цена - дешевле

Для того, чтобы когда с улицы забирается воздух с температурой -30 градусов, нагревателю было проще работать. Делаем аля рекуператор.

**Comment by kain** [comment]
Добавлю свои 5 копеек из опыта использования: в режиме "смешанный" на малых скоростях вентилятора (1-2) воздух с улицы беспрепятственно проходит в комнату через нижнюю решётку (это просто крупная сетка) с помощью естественной тяги. Короче говоря, смешанный режим на малых скоростях - это просто открытая щель.

**Comment by artkos2** [comment]
Бывает и интересный глюк, когда включаешь бризер, он включается с заслонкой "из комнаты". Хотелось бы управоять этим.
и да, соглашусь,  смешанный работает на 3+ скорости, на малых бесполезен.

**Comment by dummylabs** [comment]
Присоединюсь, были случаи, когда с пульта промахивались и вместо кнопки изменения скорости нечаянно меняли режим забора воздуха. Отследить это получалось только по неприятному запаху из бризера.

**Comment by airens** [comment]
@Daemon256 , @kain Добавил управление заслонкой, просьба проверить у себя

**Comment by Buterbrott** [comment]
После обновления ошибки в логе и  magicair не отдает температуру
`2021-03-04 22:34:55 ERROR (MainThread) [homeassistant.components.sensor] Platform tion does not generate unique IDs. ID 7afb7a43-c533-4085-8c26-05ae83c39d7c already exists - ignoring sensor.brizer_tion_o2_mac_1_temperature_in
2021-03-04 22:34:55 ERROR (MainThread) [homeassistant.components.sensor] Platform tion does not generate unique IDs. ID 2d8928c3-b4c2-4731-a305-e8397383356a already exists - ignoring sensor.magicair_co2
2021-03-04 22:34:55 ERROR (MainThread) [homeassistant.components.sensor] Platform tion does not generate unique IDs. ID 2d8928c3-b4c2-4731-a305-e8397383356a already exists - ignoring sensor.magicair_co2
2021-03-04 22:34:55 ERROR (MainThread) [homeassistant.components.sensor] Platform tion does not generate unique IDs. ID 3a1c81d7-58ed-4456-b673-10634e5e09f6 already exists - ignoring sensor.brizer_tion_o2_mac_2_temperature_in`

**Comment by airens** [comment]
> После обновления ошибки в логе и magicair не отдает температуру
> `2021-03-04 22:34:55 ERROR (MainThread) [homeassistant.components.sensor] Platform tion does not generate unique IDs. ID 7afb7a43-c533-4085-8c26-05ae83c39d7c already exists - ignoring sensor.brizer_tion_o2_mac_1_temperature_in 2021-03-04 22:34:55 ERROR (MainThread) [homeassistant.components.sensor] Platform tion does not generate unique IDs. ID 2d8928c3-b4c2-4731-a305-e8397383356a already exists - ignoring sensor.magicair_co2 2021-03-04 22:34:55 ERROR (MainThread) [homeassistant.components.sensor] Platform tion does not generate unique IDs. ID 2d8928c3-b4c2-4731-a305-e8397383356a already exists - ignoring sensor.magicair_co2 2021-03-04 22:34:55 ERROR (MainThread) [homeassistant.components.sensor] Platform tion does not generate unique IDs. ID 3a1c81d7-58ed-4456-b673-10634e5e09f6 already exists - ignoring sensor.brizer_tion_o2_mac_2_temperature_in`

вроде бы исправил, заберите последнюю версию

**Comment by Buterbrott** [comment]
Спасибо! Работает
