### ISSUE TITLE
Сам меняется режим работы

### ISSUE THREAD

**Issue by MihVS** [airens/tion_home_assistant#15]
До обнов у меня настроено было по принципу перепроверки заданного статуса и отправки команды вновь если статус не изменился, но после обновления стал замечать что это не стало работать. Отправленная команда бывает возвращается с большой задержкой. Т.е. например изменил я режим с обогрева на вентиляцию, всё изменилось, делаю проверку всё ок и примерно через 30 сек может статус сам вернутся на обогрев. Не знаю с чем это связано, но очень неудобно стало контролировать исполнение команд. Если я убираю проверку, то команды не всегда проходят с первого раза. Сейчас думаю как откатиться обратно, где всё работало как надо)

**Comment by airens** [comment]
Последнее обновление библиотеки и компонента было полгода назад, вы о каком обновлении говорите?

**Comment by MihVS** [comment]
Я извиняюсь, невнимателен, не туда написал) думал одна только интеграция, оказывается у вас ещё есть.
