### ISSUE TITLE
Кнопка применить настройки расписания

### ISSUE THREAD

**Issue by modsamara** [airens/tion_home_assistant#16]
В родном приложении есть кнопка "Применить настройки расписания", можно ли ее реализовать средствами данной интеграции?
Суть в том, что настроено расписание работы и режимы, в определенный момент мы например хотим просто выключить бризер(ну дует кому-то в макушку например). Выключаем, а включить в прежний режим уже не можем, лезем в родное приложение и нажимаем вышеназванную кнопку.

**Comment by airens** [comment]
Я не вижу смылса усложнять интеграцию функцией, которая, при управлении бризером из умного дома, просто не нужна, поскольку вы сами можете сделать любое расписание и любую логику работы при помощи Home Assistant.
