### ISSUE TITLE
Опрос других параметров Tion

### ISSUE THREAD

**Issue by Vittaly76** [airens/tion_home_assistant#18]
Добрый день. В данном плагине на текущий момент организован периодический сбор значений ограниченного кол-ва параметров: только температура на входе и на выходе. Остальные значения можно только задавать, но не получать их значения на периодической основе. Вопрос: как можно организовать периодический опрос других параметров? Например, режим работы вентилятора (авто/ручной), текущая скорость вентилятора, индикатор замены фильтров?

**Comment by airens** [comment]
Чем атрибуты бризера не устраивают? Там все есть

**Comment by Vittaly76** [comment]
> Чем атрибуты бризера не устраивают? Там все есть

Там действительно всё есть, но они не обновляются самостоятельно на периодической основе, пока не вызовешь какой-либо сервис (например, пока не изменишь режим работы вентилятора вручную).

**Comment by airens** [comment]
Это тогда проблема HA, а не компонента. Вы можете использовать Update Entity, чтобы принудительно запросить новые значения атрибутов
