### ISSUE TITLE
Не работает выбор источника забора воздуха

### ISSUE THREAD

**Issue by martkotur** [airens/tion_home_assistant#21]
Не работает выбор источника забора воздуха 0 - из дома, 1 - смешанный, 2 - улица
При любом значении принудительно включает забор из помещения.
В логе только это
2021-04-09 08:33:48 INFO (SyncWorker_17) [custom_components.tion.climate] Setting zone mode to manual
2021-04-09 08:33:51 INFO (SyncWorker_17) [custom_components.tion.climate] Setting breezer fan_mode to 3

UPD: В кабинете magic air аналогичная проблема. Включается только забор из комнаты. Служба поддержки Тион сообщила, что веб сервис выводится из эксплуатации и не поддерживается с 2019 года. Пользуйтесь приложением.

**Comment by airens** [comment]
Интеграция повторяет функционал веб-интерфейса, т.к. использует его протокол. Соответственно, на данный момент, я ничего сделать не могу
