### ISSUE TITLE
current_temperature\temperature 

### ISSUE THREAD

**Issue by EvgenyPanchenko** [airens/tion_home_assistant#23]
Значение `current_temperature` показывает значение на выходе из бризере и оно всегда равно  значению сенсора `sensor.tion_breezer_3s_temperature_out `
Возможно поменять значение `current_temperature` на текущее значение температуры в комнате, но из внешнего датчика в Magic Air или модуле CO2, что более соответствует названию?
Да и текущее значение температуры помещения получается нигде не присутствует

Переименовать атрибут `temperature` в `set_temperature` или  `target_temperature` так как значение соответствует выставленной целевой температуры нагрева выходящего воздуха. Новое имя будет более точно описывать значение

**Comment by airens** [comment]
`current_temperature` - стандартный атрибут Home assistant, поэтому он должен заполняться. Температура от CO2 и MagicAir находятся в соответствующих `entity`, используйте их, а бризер тут не при чём.
