### ISSUE TITLE
Tion 4s

### ISSUE THREAD

**Issue by AlexeyTorch** [airens/tion_home_assistant#24]
Добрый день.
интеграция установилась, устройство обнаруживается:
hvac_modes:
  - fan_only
min_temp: 0
max_temp: 25
target_temp_step: 1
fan_modes:
  - 'off'
  - auto
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
current_temperature: 30
fan_mode: 2
mode: manual
target_co2: 800
speed: 2
speed_min_set: 0
speed_max_set: 6
filter_need_replace: false
t_in: 29
gate: inside
friendly_name: Спальня Tion 4S
icon: mdi:air-filter
supported_features: 8

При попытке включить/поменять [режим]
service: climate.set_fan_mode
data:
  fan_mode: '2:2'
target:
  entity_id: climate.spalnia_tion_4s

возникает ошибка:
2021-07-14 20:55:46 INFO (SyncWorker_9) [custom_components.tion.climate] Setting breezer fan_mode to 1
2021-07-14 20:55:47 ERROR (SyncWorker_9) [tion] TionApi parameters set bad_request: heater_mode should be presented

**Comment by aqjol21** [comment]
![image](https://user-images.githubusercontent.com/26284578/127476315-9697256d-52af-4253-84a6-83ee1a46a200.png)

**Comment by airens** [comment]
Здравствуйте, у вас модель 4S, добавил поддержку

**Comment by aqjol21** [comment]
> Здравствуйте, у вас модель 4S, добавил поддержку - проверьте

Спасибо

**Comment by AlexeyTorch** [comment]
Да, работает. заявку можно закрывать
