### ISSUE TITLE
Tion 4S не работает режим обогрева из HA

### ISSUE THREAD

**Issue by ghostkaa** [airens/tion_home_assistant#25]
В карточке устройства присутствует только вентиляция, в свойствах объекта climate.tion_breezer_4s_1 указано hvac_modes: fan_only. Если обогрев был включен через родное приложение, то изменение скорости через home assistant выключает обогрев.

**Comment by stanmarsh1101** [comment]
Подтверждаю, обогрев недоступен

**Comment by ilvi80** [comment]
Удалось решить проблему?

**Comment by stanmarsh1101** [comment]
Update, problem is persistent

**Comment by ilvi80** [comment]
Уважаемый разработчик!
Стоит ли нам ожидать обновления и исправления данной ошибки? Ответьте, пожалуйста.

**Comment by ghostkaa** [comment]
Да, работает. Спасибо большое!
