### ISSUE TITLE
Бризер О2 иногда отваливается.

### ISSUE THREAD

**Issue by rbalaev** [airens/tion_home_assistant#29]
Здравствуйте. Стоит два бризера o2 одинаковые, один иногда ведет себя так в ХА
![image](https://user-images.githubusercontent.com/90223039/142776157-04ce2512-0782-4833-9c78-3dba4e232838.png)
При этом в родном приложении все нормально.

**Comment by airens** [comment]
[https://github.com/airens/tion_home_assistant/blob/master/ISSUE_TEMPLATE.md](url)
