### ISSUE TITLE
Tion O2

### ISSUE THREAD

**Issue by mr1606** [airens/tion_home_assistant#3]
Добрый день ! Установил Ваш плагин, но климатическое устройство не создалось. Т. Е. Графики наблюдаю, а управлять устройством не могу. Скажите, тион О2 поддерживается? Если да, то чего необходимо сделать, что бы можно было управлять устройствами? В логах каких-то ошибок не наблюдаю.

**Comment by airens** [comment]
Теперь O2 должен работать
