### ISSUE TITLE
Tion 4s Homekit

### ISSUE THREAD

**Issue by bisquit2003** [airens/tion_home_assistant#32]
Здравствуйте
имеют tion 4s, добавил интеграцию, все ок, управляется из ha
но при пробросе в Homekit добавилось все, кроме управления вентилятором бризера. подскажите, пожалуйста, как добавить, прошу не пинать, опыт в ha 2 дня

**Comment by airens** [comment]
По Homekit ничего не подскажу - не пользуюсь
