### ISSUE TITLE
Поддержка термоголовки Danfoss Eco

### ISSUE THREAD

**Issue by kirillovserg** [airens/tion_home_assistant#35]
Добрый день.
Премного благодарен за столь полезную интеграцию! Всё чудесно работает.

Вопрос - нет ли возможности добавить поддержку умной термоголовки Danfoss Eco?
https://tion.ru/shop/danfoss-eco/
Для неё в приложении тиона отдельно задаётся целевая температура, хочется и этим параметром управлять из HA.
Спасибо.

**Comment by AX0411** [comment]
https://github.com/HBDK/Eco2-Tools

**Comment by airens** [comment]
Вот [тут](https://github.com/vanstolyarov/tion_home_assistant/tree/thermostat) автор вроде бы как добавил поддержку, но, поскольку не стал нормально оформлять свой код, эта версия теперь существует отдельно.
