### ISSUE TITLE
новая версия интеграции

### ISSUE THREAD

**Issue by bisquit2003** [airens/tion_home_assistant#36]
Здравствуйте
обновил сегодня интеграцию, увидел что там появился вариант "выключено"
вроде ничего нового больше
однако бризер теперь не реагирует на включение обогрева
даже если я включу в приложении тион, в ха не изменится состояние бризера

tion 4s

апд: управление вентиляцией из ха (сокростью) работает, выключение работает, только нагревать не включается
проверено на 2 бризерах и станции magic air + modul co2

**Comment by timex370** [comment]
+1
Tion 4s
Более того, когда в HA устанавливаешь режим работы "обогрев" , обогрев на тион отключается
Если включаешь обогрев через родное приложение, в HA статус не изменяется. Остаётся режим "вентиляция".

Что-то поломалась...

**Comment by bisquit2003** [comment]
> +1 Tion 4s Более того, когда в HA устанавливаешь режим работы "обогрев" , обогрев на тион отключается Если включаешь обогрев через родное приложение, в HA статус не изменяется. Остаётся режим "вентиляция".
> 
> Что-то поломалась...

может знаете как откатиться? а то не нашел выбора версии интеграшки при установке

**Comment by timex370** [comment]
пытаюсь разобраться в коде
вижу, что `HVAC_MODE_HEAT` крутиться вокруг `self._breezer.heater_enabled`

Однако, в ответе API нет такого атрибута.
Там только `heater_mode: 'heat'` или `heater_mode: 'maintenance'`

```
{
            "guid": "...",
            "name": "4S/2",
            "type": "breezer4",
            "subtype_d": 0,
            "control_type": "rf",
            "mac": "...",
            "mac_long": ...,
            "temperature_control": "absolute",
            "is_online": true,
            "last_seen_delta": 0,
            "zone_hwid": 500143889,
            "max_speed": 6,
            "serial_number": "null",
            "order": 1,
            "data": {
              "heater_type": "1.4kvt",
              "heater_mode": "maintenance",
              "breezer_work_air": 24523330,
              "electronic_work_seconds": 11660041,
              "sound_is_on": false,
              "t_power_board": 39,
              "t_main_board": 25,
              "heater_power": 0,
              "any_active_timer": false,
              "controlled_by_magic_air": true,
              "last_command_source": "interface",
              "status": "application",
              "is_on": true,
              "data_valid": true,
              "is_auto": true,
              "speed": 2.0,
              "speed_max_set": 2,
              "speed_min_set": 1,
              "speed_limit": 6.0,
              "t_in": 18.0,
              "t_set": 20.0,
              "t_out": 19.0,
              "gate": 0,
              "filter_time_seconds": 8377972,
              "filter_need_replace": false,
              "signal_level": 173,
              "backlight": 1,
              "turbo_mode_is_active": false,
              "turbo_mode_elapsed_seconds": 0,
              "turbo_mode_error_code": 0,
              "measurement_time_iso": "2022-10-06T09:25:27.0000000",
              "measurement_time": 1665048327,
              "errors": {
                "code": "0x00000000",
                "list": []
              }
            },
            "firmware": "02E0",
            "hardware": "0001",
            "t_max": 30.0,
            "t_min": 0.0,
            "creation_time": 1652420272,
            "update_time": 1652423244
          }
```

**Comment by timex370** [comment]
Ну т.е. для 4S в tion.py стр. 797 `self.heater_enabled`  надо отстраивать от `heater_mode`
А в стр. 754, когда формируем отправку команды, для 4S отправлять не `heater_enabled`,  а `heater_mode: 'heat'/'maintenance'`

**Comment by timex370** [comment]
только вот теперь не могу понять, почему тогда в предыдущей версии у меня получалось включать `heat` через интерфейс HA

**Comment by timex370** [comment]
Чтобы `heat` для 4S включался, надо:
https://github.com/airens/tion_home_assistant/blob/3e79111995adfac942f87da56a5f68ece7943f46/custom_components/tion/climate.py#L187
```
self._breezer.send(extra_data={"heater_mode": "heat"})
```

Чтобы `heat` для 4S отображался (изменял состояние в HA) придется менять код в tion api
https://github.com/airens/tion/blob/1e17df366ea5e9560aafd692b5c60cb24268a60c/tion/tion.py#L242
```
self.heater_enabled = data.get("heater_enabled", data.get("heater_mode") == 'heat')  # True
```

... если я правильно все понял

**Comment by ilvi80** [comment]
подтверждаю, что-то поламалось, обогрев теперь не включается их ХА, только из родного приложения

**Comment by airens** [comment]
Tion, похоже, обновил протокол обмена в части работы с нагревателем. Обновил библиотеку и компонент. У меня есть на данный момент только 4S для экспериментов, поэтому смог проверить только на  нем. Просьба проверить работу на других устройствах

**Comment by airens** [comment]
> Чтобы `heat` для 4S включался, надо:
> 
> https://github.com/airens/tion_home_assistant/blob/3e79111995adfac942f87da56a5f68ece7943f46/custom_components/tion/climate.py#L187
> 
> ```
> self._breezer.send(extra_data={"heater_mode": "heat"})
> ```
> 
> Чтобы `heat` для 4S отображался (изменял состояние в HA) придется менять код в tion api https://github.com/airens/tion/blob/1e17df366ea5e9560aafd692b5c60cb24268a60c/tion/tion.py#L242
> 
> ```
> self.heater_enabled = data.get("heater_enabled", data.get("heater_mode") == 'heat')  # True
> ```
> 
> ... если я правильно все понял

да, совершенно верно

**Comment by bisquit2003** [comment]
спасибо, все починилось

**Comment by airens** [comment]
> спасибо, все починилось
Какой у вас бризер?

**Comment by timex370** [comment]
Да, спасибо большое за оперативность.

У меня две зоны MagicAir + 4S и CO2 модуль + 4S

**Comment by bisquit2003** [comment]
> Какой у вас бризер?
так же:
У меня две зоны MagicAir + 4S и CO2 модуль + 4S

**Comment by airens** [comment]
Похоже, проблема действительно была только у владельцев 4S
