### ISSUE TITLE
Добавить управления термо-головками danfoss eco через компонент

### ISSUE THREAD

**Issue by Sol1in** [airens/tion_home_assistant#39]
У меня 4 комнаты в каждому MagicAir + бризер и термо-головки управления отоплением. Со всех данные в HA приходят (правда, каждый элемент приходит как набор отдельных сенсоров, что не всегда удобно, но не страшно). Единственное чего не хватает - это возможности управления заданной температурой на термо-головках Danfoss Eco. Они видны, определяются как термостат, текущую температуру видно, а задать целевую - нет :-(

**Comment by airens** [comment]
У меня нет таких головок, поэтому сделать не могу.

**Comment by Sol1in** [comment]
Тогда, может быть, наводку дашь как можно в логи чистые пакеты отправить? А то по указанным параметрам в лог HASS ничего не попадает... я попробую сам разобраться.

**Comment by airens** [comment]
1. Сырые данные можно получить используя саму [библиотеку](https://github.com/airens/tion), а не компонент.
2. Вот [тут](https://github.com/airens/tion_home_assistant/pull/11/commits/06b70d2d2309efe57c398f670124be805d0e75a6) товарищ вроде бы делал поддержку, но, поскольку не привел свой код в порядок по стилю,  я этот коммит не включил.
