### ISSUE TITLE
Данные для автоматического управления скоростью притока

### ISSUE THREAD

**Issue by mr1606** [airens/tion_home_assistant#4]
Когда ставлю режим скорости авто - откуда берется целевое значение уровня CO2, до которого тион должен опустить уровень?

**Comment by airens** [comment]
Атрибут `target_co2`. В HA нет такого понятия, как уровень CO2, поэтому я не придумал, как интегрировать возможность задания этого параметра при помощи вызова службы или иным способом. Устанавливайте через официальное приложение, если вам нужно.

**Comment by mr1606** [comment]
> Атрибут `target_co2`. В HA нет такого понятия, как уровень CO2, поэтому я не придумал, как интегрировать возможность задания этого параметра при помощи вызова службы или иным способом. Устанавливайте через официальное приложение, если вам нужно.

Я так и подумал. Спс за разъяснение. Думаю, тогда будет логичнее написать свою автоматизацию.

**Comment by dima11235** [comment]
Добрый день. Скажите, пожалуйста, есть ли возможность сделать установку целевого уровня CO2 через функцию set_mode, например также как вы это сделали для диапазона скоростей? Т.е. например указать диапазон скоростей, а через ":" желаемый уровень CO2. Пример "0-2:950".
