### ISSUE TITLE
Tion Clever

### ISSUE THREAD

**Issue by gryablik** [airens/tion_home_assistant#40]
Добрый день.
Добавьте пожалуйста в интеграцию Tion Clever.

Эта ошибка возникла в кастомной интеграции.

Logger: tion
Source: custom_components/tion/__init__.py:54
Integration: Tion (documentation, issues)
First occurred: 08:48:00 (1 occurrences)
Last logged: 08:48:00

Unknown device type: tionClever, contact the developer for support with data: TionZonesDevices guid = 917f0125-9212-482c-b03d-32b5e7757d83 name = Clever_L_Bedroom type = tionClever subtype_d = 0 control_type = rf mac = 68:53:F3:15:91:45 mac_long = 76489440842600 is_online = True last_seen_delta = 0 zone_hwid = 500143889 serial_number = A2012DEFSN order = 1 data = TionZonesDevicesData() firmware = 0009 hardware = 0001 creation_time = 1673621195 update_time = 1673621392 temperature_control = None max_speed = 2 t_max = None t_min = None

**Comment by airens** [comment]
Добрый, боюсь, я не смогу добавить поддержку не имея устройства. Можете либо попробовать сделать сами по аналогии, либо подождать, что кто-то из владельцев-программистов сделает.
