### ISSUE TITLE
Для 3S1 нет отдельного управления на выбор потока воздуха улица/смешанный/изнутри

### ISSUE THREAD

**Issue by albataev** [airens/tion_home_assistant#41]
Иногда бризер включается на забор воздуха из помещения, что неудобно - нужно смотреть через родное приложение.

**Comment by albataev** [comment]
Пример:

# setting air source to outside
breezer.gate = 2

**Comment by airens** [comment]
То, что вы смотрите - параметр только для чтения, гейт задается через `set_fan_mode` (см. README)
