### ISSUE TITLE
Не переключается режим забора воздуха

### ISSUE THREAD

**Issue by Yari117** [airens/tion_home_assistant#44]
Переключение режима забора воздуха не работает, например set fan mode "2:0" не переводит бризер в режим забора воздуха из комнаты. Бризер переключает скорости, но не меняет режим забора воздуха "3:0" после "2:0" увеличивает скорость, т.е. реакция на команду есть, но заслонка не меняет своего положения. Пробовал и "0" и "1" и "2", ничего не меняется. В оф. приложении переключить режим забора воздуха получается, заслонка двигается.

Другие команды работают: выключение, авто-режим, ручной режим

**Comment by airens** [comment]
Здравствуйте, какой прибор у вас?

**Comment by Yari117** [comment]
> Здравствуйте, какой прибор у вас?

Спасибо за ответ! Прошу прощения, не написал - Tion 4S

**Comment by airens** [comment]
Подлил изменения Дмитрия (@RealLord). Спасибо ему!
