### ISSUE TITLE
Управление расписанием MagicAir

### ISSUE THREAD

**Issue by vmishurov** [airens/tion_home_assistant#45]
В приложении MagicAir есть расписание работы бризера.
Есть ли возможность добавить в API хотя бы минимальную его поддержку.? Включить/выключить работу шедулера.

Поясню зачем. Допустим мы открываем окно в комнате, где установлен бризер.
Логично автоматизацией выключить бризер пока окно открыто.
Но если включен шедулер он вновь включит бризер при наступлении какого-то времени в расписании.

**Comment by airens** [comment]
Здравствуйте, я не использую расписание, т.к. сам Home Assistant даёт более богатые возможности, чем родное приложение. Если у вас есть такая потребность - можете реализовать самостоятельно и сделать `Pull Request`
