### ISSUE TITLE
Не работает после обновления операционной системы haas. Сегодняшний апдейт. Говорит объекты больше не предоставляются интеграцией 

### ISSUE THREAD

**Issue by Ontry57** [airens/tion_home_assistant#47]
# Внимание

Если у вас что-то не работает, убедитесь, что:

1. используете последнюю версию компонента
2. используете последнюю версию Home Assistant

Если все вышеуказанное справедливо, то выполните следующее:

1. Включите расширенное логирование компонента `tion_home_assistant` и модуля `tion`, как описано в `README.md`
2. Укажите модель своего устройства и версию компонента
3. Опишите подробно, что работает не так
4. Опишите, как можно повторить ошибку:

- если меняете что-то через интерфейс - опишите, какие значения были установлены до изменения и что стало после
- если используете службы, то укажите какую именно службу вызываете и с какими параметрами (в виде `json` или `yaml`)

5. Приложите части `.log` файла, которые касаются компонента `tion_home_assistant` и модуля `tion`

`Issue`, несоответствующие вышеописанному будут закрываться.

**Comment by ilvi80** [comment]
Да, интеграция отвалилась полностью. Если до этого не работало переключение режимов, то теперь и станция отвалилась.
Ждем решения...

**Comment by airens** [comment]
Друзья, я сам словил кучу отвалов интеграций на последнем обновлении, поэтому ближайшие пару месяцев переходить на новую версию не буду. В связи с этим и исправлять эту интеграцию пока возможности нет. На данный момент совет откатиться до предыдущей версии HA либо, кто может, поправить самостоятельно и кинуть pull request.

**Comment by kirillovserg** [comment]
Поставил обновление 2024.1.3, всё снова заработало.

**Comment by RealLord** [comment]
Да в версии 2024.1.3 частично заработал tion.
Видится MagicAir, с него показания снимаются.
Но управление самим бризером не работает, из-за ошибки в НА.
Встроенная функция НА set_fan не работает

**Comment by RealLord** [comment]
Обновил компонент, вроде все что хотел сделал.
Описание: https://github.com/RealLord/tion_home_assistant
У меня 5 бризеров дома, в кабинетах, в спальне, в гостинной.
Все работает стабильно, на 3S/4S.

4 бризера работают по пресету:

два по SLEEP в спальнях в 21:00
два в кабинетах по пресету ACTIVITY в 08:00
Один по CO2 от Air Magic в гостиной по скрипту, который раз в минуту запускается, определяет СО2 и выставляет скорость вентилятора.

**Comment by airens** [comment]
Подлил изменения Дмитрия (@RealLord). Спасибо ему!
