### ISSUE TITLE
Возможность установки целевого уровня CO2

### ISSUE THREAD

**Issue by dima11235** [airens/tion_home_assistant#6]
Добрый день. Большое спасибо за библиотеку для HA! Скажите, пожалуйста, есть ли возможность сделать установку целевого уровня CO2 через функцию fan_mode, также как вы это сделали для диапазона скоростей? Т.е., например, указать диапазон скоростей, а через ":" желаемый уровень CO2 - "0-2:950".

**Comment by airens** [comment]
Хорошая идея, сделал
