### ISSUE TITLE
Если в set_fun_mode не задано целевое значение CO2, то оно сбрасывается на 900.

### ISSUE THREAD

**Issue by dima11235** [airens/tion_home_assistant#7]
Добрый день! Большое спасибо за добавленную возможность управлять целевым СО2. Все работает, единственная особенность - если в set_func_mode не задано значение CO2, то значение установленное в бризере сбрасывается  на 900. Возможно, что функция пытается отправить на бризер значение None.

**Comment by airens** [comment]
Ещё раз, подробнее, что делаете, что получаете

**Comment by dima11235** [comment]
1. Устанавливаю значение значение параметра target_co2 например на 1200 (либо с помощью вызова climate.set_fan_mode c fan_mode:"0-2:1000", либо из приложения управления бризером.
2. Проверяю параметр бризера  target_co2. Он равен 1200.
2. После этого вызываю climate.set_fan_mode c fan_mode:"1".
3. Параметр бризера  target_co2 сбрасывается на 900.

Такое ощучение, что в функции set_fan_mode вашего пакета, нужно строчку
125: new_co2 = None
исправить на 
new_co2 = self._zone.target_co2

**Comment by airens** [comment]
Исправил, проверьте
