### ISSUE TITLE
Бризер переключается в режим рециркуляции

### ISSUE THREAD

**Issue by dima11235** [airens/tion_home_assistant#8]
Добрый день. Некоторое время назад (неделю-две-три) появился эффект, что при выводе бризера S3 из автоматического в ручной режим (например, из режима "0-2:750" в "0" (выключить совсем) или на скорость "2") бризер переключается из режима забора воздуха снаружи в режим рециркуляции. Попытки понять причину показали, что подобные ситуации возникают и если делать переключения через Web-интерфейс Tion. Там тоже периодически забор воздуха с улицы переключается на комнату если переводить бризер из автоматического в ручной режим. Скорее всего это баг или особенность логики работы Web интерфейса. Запрос в поддержке Tion я разместил, но не факт что они будут исправлять. Пытался проработать воркэраунд, но ничего не получается, т.к. переключение забора воздуха происходит или не происходит случайным образом при одних и тех же действиях и состояниях бризера.

Скажите, пожалуйста, есть ли возможность добавить функцию установки режима забора воздуха?
Или, например, включить возможность при выполнении любой команды принудительно включать режим забора воздуха снаружи?

**Comment by airens** [comment]
Это действительно проблема Tion. Могу порекомендовать 2 варианта:
1. Вместо мануального режима использовать автоматический (например, вместо скорости 2 использовать автоматический режим 2:2). Я использую только авто, никаких проблем уже больше года
2. Исправить climate.py у себя на инстансе следующим образом: в начале всех функций `set_...` добавить строчку `self._breezer.gate = 2` и понаблюдать. Если поможет - добавлю в следующей версии.

**Comment by dima11235** [comment]
Добрый день! Да, если оставлять бризер только в автоматическом режиме, то он не переключает забор воздуха. У меня проблема возникла потому, что я сделал автоматическое отключение бризера, когда соседи курят на балконе :). Для отключения ставлю скорость 0, при этом он переключается в ручной режим и периодически переходит на рецеркуляцию. Часто это случается, если скорость бризера была 0 в момент отключения. Правда иногда бывает, что бризер возвращается в режим забора воздуха снаружи, если снова перевести его в автоматический режим. Все очень нестабильно. Хотелось бы определенности))) Сначала попробую ваше предложение с self._breezer.gate = 2. Спасибо!

**Comment by airens** [comment]
Даже интересно стало, как вы автоматически определяете, что соседи курят на балконе?

**Comment by dima11235** [comment]
Повесил на окно датчик движения и направил его на балкон соседей)) По датчику отключаю бризер, а потом включаю его по таймеру. Вариант с 0:0 пробовал, это тоже переводит бризер в ручной режим, действует точно также как просто 0.

**Comment by airens** [comment]
весьма находчиво) Положил новую версию компонента. В атрибутах теперь есть текущее состояние рециркуляции (`gate`), чтобы легче было отслеживать

**Comment by dima11235** [comment]
Добрый день. Провел эксперимент с self._breezer.gate = 2. К сожалению, при переводе бризера в ручной режим, по прежнему бризер переключается в режим рециркуляции. Если бризер перешел в режим рециркуляции и остается в ручном режиме, то изменение скорости не приводит к переключению на забор воздуха снаружи. Если перевести бризер в автоматический режим, то он возвращается в режим забора воздуха снаружи. Звонила поддержка Tion, я еще раз описал проблему. Сказали, что передадут ее разработчикам сайта )).

**Comment by dima11235** [comment]
Пока похоже остается только вариант использования автоматического режима.

**Comment by bezkod** [comment]
при ручном переключении нужно посылать в payload еще 
'gate':'2'
и тогда всегда будет режим "с улицы"

**Comment by re3lex** [comment]
тоже столкнулся с данной проблемой.
@airens, есть ли возможность починить компнент, используя фикс, предложенный @bezkod ?

**Comment by airens** [comment]
> тоже столкнулся с данной проблемой.
> @airens, есть ли возможность починить компнент, используя фикс, предложенный @bezkod ?

это не решение проблемы, а обход косяков производителя девайса. Я посылаю тот режим, который дает на данный момент сервер, если пользователь принудительно не задал иное (см. "фикс" от @bezkod). Отправка всегда режима "с улицы" невозможна, т.к. некоторые люди **хотят** использовать смешанный режим или режим рециркуляции, а я его буду таким образом игнорировать или перебивать. Пока производитель не починит проблему - используйте автоматический режим, как я описал выше, либо задавайте режим принудительно, не вижу в этом ровным счетом никаких проблем.

**Comment by re3lex** [comment]
> используйте автоматический режим, как я описал выше, либо задавайте режим принудительно
Да я с удовольствием, только я управляю из интерфейса, а там состояние режима проветривания не сразу меняется (если вообще меняется).

**Comment by airens** [comment]
> > используйте автоматический режим, как я описал выше, либо задавайте режим принудительно
> 
> Да я с удовольствием, только я управляю из интерфейса, а там состояние режима проветривания не сразу меняется (если вообще меняется).
HA нормально не умеет работать с таким устройством, как проветриватель, поэтому интерфейс ущербен. Используйте Switch+Input number+автоматизации или скрипты с нужными параметрами.

**Comment by re3lex** [comment]
ок, понял. Спасибо за совет!
